title: Drake's D&D5e Table-Rules
description: 
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
logo: zzImages/Dungeons-And-Dragons-Logo-PNG-File.png
aux_links:
search_enabled: true
search.rel_url: false